
syntax = "proto3";

package maps;

service Maps {
  rpc Geocode(GeocodeRequest) returns (GeocodeResponse);
  rpc ReverseGeocode(ReverseGeocodeRequest) returns (ReverseGeocodeResponse);
  rpc GetRoute(GetRouteRequest) returns (GetRouteResponse);
}

message GeocodeRequest {
  string address = 1;
}

message GeocodeResponse {
  Location location = 1;
}

message ReverseGeocodeRequest {
  Location location = 1;
}

message ReverseGeocodeResponse {
  string address = 1;
}

message GetRouteRequest {
  Location start = 1;
  Location end = 2;
}

message GetRouteResponse {
  repeated Location path = 1;
  double distance = 2;
  double duration = 3;
}

message Location {
  double lat = 1;
  double lng = 2;
}
