export const API_CONFIG = {
  BASE_URL: process.env.EXPO_PUBLIC_API_URL || 'http://0.0.0.0:3000/api',
  TIMEOUT: 30000,
  RETRY_ATTEMPTS: 3,
  RETRY_DELAY: 1000,
};

export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    VERIFY_EMAIL: '/auth/verify-email',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    ME: '/auth/me',
  },
  USER: {
    PROFILE: '/users/profile',
    UPDATE_PROFILE: '/users/profile',
    UPDATE_GENDER_PREFERENCE: '/users/gender-preference',
    DEVICE_TOKEN: '/users/device-token',
    NOTIFICATIONS: '/users/notifications',
    NOTIFICATION_READ: (id: string) => `/users/notifications/${id}/read`,
    NOTIFICATIONS_READ_ALL: '/users/notifications/read-all',
    NOTIFICATION_PREFERENCES: '/users/notifications/preferences',
  },
  RIDE: {
    ESTIMATE: '/rides/estimate',
    REQUEST: '/rides/request',
    HISTORY: '/rides/history',
    CANCEL: (rideId: string) => `/rides/${rideId}/cancel`,
  },
  POOL: {
    CREATE: '/pools',
    CREATE_ALT: '/pools/create',
    GET_BY_ID: (poolId: string) => `/pools/${poolId}`,
    JOIN: (poolId: string) => `/pools/${poolId}/join`,
    LEAVE: (poolId: string) => `/pools/${poolId}/leave`,
    CANCEL: (poolId: string) => `/pools/${poolId}/cancel`,
    SEARCH: '/pools/search',
    ROUTE: (poolId: string) => `/pools/${poolId}/route`,
    PREVIEW: (poolId: string) => `/pools/${poolId}/preview`,
    COMBINED_ROUTE: (poolId: string) => `/pools/${poolId}/combined-route`,
    UPDATE_COMBINED_ROUTE: (poolId: string) => `/pools/${poolId}/combined-route/update`,
    FARE: (poolId: string) => `/pools/${poolId}/fare`,
    EXTEND_SEARCH: (poolId: string) => `/pools/${poolId}/extend-search`,
    COMPLETE_SEARCH: (poolId: string) => `/pools/${poolId}/complete-search`,
    // FREE Google Maps navigation - no API cost, uses native app
    NAVIGATION_LINK: (poolId: string) => `/pools/${poolId}/navigation-link`,
  },
  DRIVER: {
    GO_ONLINE: '/driver/go-online',
    GO_OFFLINE: '/driver/go-offline',
    STATUS: '/driver/status',
    UPDATE_LOCATION: '/driver/location',
    AVAILABLE_POOLS: '/driver/available-pools',
    ACCEPT_POOL: (poolId: string) => `/driver/pools/${poolId}/accept`,
    REJECT_POOL: (poolId: string) => `/driver/pools/${poolId}/reject`,
    ACTIVE_POOL: '/driver/active-pool',
    START_RIDE: '/driver/ride/start',
    COMPLETE_RIDE: '/driver/ride/complete',
    PICKUP: (passengerId: string) => `/driver/pickup/${passengerId}`,
    DROPOFF: (passengerId: string) => `/driver/dropoff/${passengerId}`,
    EARNINGS_TODAY: '/driver/earnings/today',
    EARNINGS_HISTORY: '/driver/earnings/history',
    STATS: '/driver/stats',
    PRIORITY_LOCATION: '/driver/priority-location',
  },
  PAYMENT: {
    PROCESS: '/payments/process',
    HISTORY: '/payments/history',
  },
  WALLET: {
    BALANCE: '/wallet/balance',
    ADD_FUNDS: '/wallet/add-funds',
    WITHDRAW: '/wallet/withdraw',
    TRANSACTIONS: '/wallet/transactions',
  },
  MESSAGING: {
    SEND: '/messages',
    CONVERSATIONS: '/messages/conversations',
    GET_MESSAGES: (conversationId: string) => `/messages/${conversationId}`,
    MARK_READ: (messageId: string) => `/messages/${messageId}/read`,
  },
  PRIYO_SATHI: {
    LIST: '/priyo-sathi',
    ADD: '/priyo-sathi',
    REMOVE: (companionId: string) => `/priyo-sathi/${companionId}`,
    BLOCK: (companionId: string) => `/priyo-sathi/${companionId}/block`,
    PENDING_REQUESTS: '/priyo-sathi/requests',
    RESPOND_REQUEST: (requestId: string) => `/priyo-sathi/requests/${requestId}/respond`,
    INVITE_TO_RIDE: (companionId: string) => `/priyo-sathi/${companionId}/invite`,
    NEARBY: '/priyo-sathi/nearby',
    GET_RIDE_INVITE: (rideId: string) => `/priyo-sathi/invite/${rideId}`,
    ACCEPT_RIDE_INVITE: (rideId: string) => `/priyo-sathi/invite/${rideId}/accept`,
  },
};
