export const API_CONFIG = {
  BASE_URL: process.env.EXPO_PUBLIC_API_URL || 'http://localhost:3000/api',
  TIMEOUT: 30000,
  RETRY_ATTEMPTS: 3,
  RETRY_DELAY: 1000,
};

export const API_ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    VERIFY_EMAIL: '/auth/verify-email',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
  },
  USER: {
    PROFILE: '/users/profile',
    UPDATE_PROFILE: '/users/profile',
    UPDATE_PREFERENCES: '/users/preferences',
    UPDATE_LOCATION: '/users/location',
    GET_RIDE_HISTORY: '/users/ride-history',
    GET_STATS: '/users/stats',
  },
  RIDE: {
    CREATE: '/rides',
    GET_ALL: '/rides',
    GET_BY_ID: (id: string) => `/rides/${id}`,
    UPDATE: (id: string) => `/rides/${id}`,
    CANCEL: (id: string) => `/rides/${id}/cancel`,
    SEARCH: '/rides/search',
    NEARBY: '/rides/nearby',
    START: (id: string) => `/rides/${id}/start`,
    COMPLETE: (id: string) => `/rides/${id}/complete`,
  },
  POOL: {
    CREATE: '/pools',
    GET_ALL: '/pools',
    GET_BY_ID: (id: string) => `/pools/${id}`,
    JOIN: (id: string) => `/pools/${id}/join`,
    LEAVE: (id: string) => `/pools/${id}/leave`,
    SEARCH: '/pools/search',
    GET_MEMBERS: (id: string) => `/pools/${id}/members`,
  },
  DRIVER: {
    REGISTER: '/drivers/register',
    GET_PROFILE: '/drivers/profile',
    UPDATE_PROFILE: '/drivers/profile',
    UPDATE_VEHICLE: '/drivers/vehicle',
    UPDATE_STATUS: '/drivers/status',
    GET_EARNINGS: '/drivers/earnings',
    GET_TRIPS: '/drivers/trips',
  },
  PAYMENT: {
    CREATE_METHOD: '/payments/methods',
    GET_METHODS: '/payments/methods',
    DELETE_METHOD: (id: string) => `/payments/methods/${id}`,
    SET_DEFAULT: (id: string) => `/payments/methods/${id}/default`,
    CREATE_TRANSACTION: '/payments/transactions',
    GET_TRANSACTIONS: '/payments/transactions',
  },
  WALLET: {
    GET_BALANCE: '/wallet/balance',
    ADD_FUNDS: '/wallet/add-funds',
    WITHDRAW: '/wallet/withdraw',
    GET_TRANSACTIONS: '/wallet/transactions',
  },
  MESSAGING: {
    SEND: '/messages',
    GET_CONVERSATIONS: '/messages/conversations',
    GET_MESSAGES: (conversationId: string) => `/messages/${conversationId}`,
    MARK_READ: (messageId: string) => `/messages/${messageId}/read`,
  },
  SAFETY: {
    REPORT_INCIDENT: '/safety/incidents',
    GET_EMERGENCY_CONTACTS: '/safety/emergency-contacts',
    ADD_EMERGENCY_CONTACT: '/safety/emergency-contacts',
    SHARE_TRIP: '/safety/share-trip',
  },
  RETENTION: {
    GET_ARCHIVED_DATA: '/retention/archived',
    REQUEST_DATA_EXPORT: '/retention/export',
    GET_RETENTION_STATS: '/retention/stats',
  },
};
